import fs from "fs";
import path from "path";

const DATA_DIR = path.resolve("src/data/animals");

const namePools = {
  male: [
    "Max", "Charlie", "Buddy", "Cooper", "Rocky", "Jack", "Toby", "Duke",
    "Bear", "Zeus", "Oliver", "Milo", "Leo", "Tucker", "Winston", "Oscar",
    "Louie", "Bentley", "Murphy", "Jake", "Cody", "Sam", "Riley", "Buster",
    "Apollo", "Bruno", "Diesel", "Finn", "Gus", "Hank", "Jasper", "Koda",
    "Loki", "Moose", "Nero", "Odin", "Rex", "Scout", "Thor", "Titan",
    "Ace", "Bandit", "Chief", "Dash", "Echo", "Flash", "Ghost", "Hunter",
    "King", "Major", "Ranger", "Shadow", "Spike", "Storm", "Blaze", "Chase",
    "Dexter", "Gunner", "Harley", "Kobe", "Maverick", "Nash", "Phoenix",
    "Rocco", "Rusty", "Simba", "Tank", "Vader", "Yukon", "Ziggy", "Bolt",
    "Comet", "Denver", "Enzo", "Fang", "Gizmo", "Hades", "Igor", "Jax",
    "Kane", "Mack", "Nico", "Onyx", "Pax", "Quinn", "Ragnar", "Sarge",
    "Talon", "Ulysses", "Vulcan", "Wylie", "Xander", "Yoshi", "Zane",
    "Baron", "Cyrus", "Draco", "Finnick", "Griffin", "Hawk"
  ],
  female: [
    "Luna", "Bella", "Daisy", "Lucy", "Lola", "Zoe", "Stella", "Penny",
    "Rosie", "Ruby", "Sadie", "Chloe", "Molly", "Bailey", "Sophie", "Coco",
    "Ginger", "Lily", "Mocha", "Pepper", "Maggie", "Roxy", "Gracie", "Mia",
    "Nala", "Willow", "Athena", "Callie", "Ellie", "Harper", "Ivy", "Juno",
    "Kona", "Leia", "Maple", "Nova", "Olive", "Piper", "Raven", "Sasha",
    "Trixie", "Violet", "Winnie", "Xena", "Yara", "Zelda", "Aurora",
    "Bonnie", "Cleo", "Dixie", "Eden", "Fiona", "Gemma", "Hazel", "Indie",
    "Josie", "Kiara", "Lexi", "Minnie", "Nellie", "Opal", "Poppy",
    "Remy", "Skye", "Tessa", "Uma", "Vera", "Wren", "Xiomara", "Yuki",
    "Aspen", "Birdie", "Cinnamon", "Dottie", "Elsa", "Flora", "Goldie",
    "Honey", "Isla", "Jasmine", "Karma", "Lacey", "Misty", "Nutmeg",
    "Peaches", "Queenie", "Rain", "Sugar", "Taffy", "Velvet",
    "Whiskey", "Xia", "Yin", "Zara", "Blossom", "Clover", "Dahlia", "Echo"
  ],
  cute: [
    "Bubbles", "Button", "Cupcake", "Doodle", "Fluffy", "Giggles", "Honey",
    "Jellybean", "Kitten", "Marshmallow", "Nugget", "Peanut", "Puddles",
    "Snuggles", "Sprinkles", "Sunny", "Tinker", "Wiggles", "Biscuit",
    "Cuddles", "Dumpling", "Fuzzy", "Gummy", "Jelly", "Kiwi", "Mochi",
    "Nibbles", "Pickles", "Pippin", "Popcorn", "Squishy", "Toffee",
    "Waffles", "Zuzu", "Boo", "Cherub", "Chip", "Cookie", "Cream Puff",
    "Dimples", "Fifi", "Gummy Bear", "Jiggly", "Lollipop", "Muffin",
    "Noodle", "Peach", "Pixie", "Pom Pom", "Pumpkin", "Roo", "Sesame",
    "Skittles", "Smiles", "Snowball", "Sparkle", "Sweet Pea", "Taffy",
    "Teddy", "Tootsie", "Twinkle", "Winky", "Baby", "Beanie", "Blinky",
    "Boba", "Bonbon", "Bubbly", "Butterbean", "Cheeks", "Cherry",
    "Churro", "Coconut", "Cotton", "Dewdrop", "Dolly", "Dot", "Faerie",
    "Gingersnap", "Glitter", "Gumdrop", "Ladybug", "Lamby", "Lulu",
    "Macaron", "Marshie", "Merry", "Milkshake", "Mopsy", "Munchkin",
    "Panda", "Peaches", "Petunia", "Pinky", "Pomelo", "Pudding",
    "Raspberry", "Rosy", "Smore", "Scooter", "Shimmer", "Shortcake",
    "Squeaky", "Star", "Sugarplum", "Tink", "Truffle"
  ],
  funny: [
    "Sir Barksalot", "Woofgang Puck", "Bark Twain", "Chewbacca",
    "Droolius Caesar", "Fuzz Aldrin", "Hairy Potter", "Jimmy Chew",
    "Meowly Cyrus", "Notorious D.O.G.", "Paw McCartney", "Salvador Dogi",
    "Taco", "Waffles", "Nacho", "Pickle Rick", "Snoop Dogg", "Bark Obama",
    "Dog Marley", "Fleaonce", "Groucho Barks", "Hulk Hogan", "Indiana Bones",
    "Jabba the Mutt", "Kanye Westie", "Lick Jagger", "Mutt Damon",
    "Neil Patrick Hairless", "Ozzy Pawsborne", "Pawdry Hepburn", "Pupperoni",
    "Quack Nicholson", "Ruffalo", "Scooby Dont", "Tater Tot", "Uggy Azalea",
    "Voldetort", "Woof Blitzer", "Xena Worrier Princess", "Yappy Gilmore",
    "Ziggy Stardog", "Bark Ruffalo", "Cat Benatar", "Doge-stoevsky",
    "Eggnog", "Fuzz Lightyear", "Goober", "Hamlet", "Hot Dog", "Iron Paw",
    "Jack Sparrow-away", "Kitty Purry", "Lil Hotdog", "Meatball",
    "Mr. Wigglesworth", "Noodle-oodle", "Olive Oyl", "Pancake",
    "Queso", "Rover Cleveland", "Sniffy Longstocking", "Toots McGee",
    "Unicorn Poop", "Veronica Corningstone", "Walnut", "Xerox",
    "Yawn DeGeneres", "Zeppelin", "Big Chungus", "Blorp", "Burrito",
    "Chairman Meow", "Chalupa", "Chubbs", "Cowboy", "Danger Noodle",
    "Ding Dong", "Donut", "Floop", "Googly Bear", "Gunk", "Hambone",
    "Jelly Roll", "Kerfuffle", "Kumquat", "Loaf", "Moo Moo", "Muggle",
    "Nugget", "Pickle Juicer", "Potato", "Quack Sparrow", "Snorlax",
    "Spaghetti", "Squid", "Tofu", "Trash Panda", "Wombat", "Zonk"
  ],
  fantasy: [
    "Aerion", "Alduin", "Aragorn", "Arwen", "Aslan", "Atreyu", "Azrael",
    "Balor", "Bastion", "Bilbo", "Celestia", "Cerberus", "Chimera",
    "Daenerys", "Draco", "Eldrin", "Elysia", "Ember", "Faelan", "Falkor",
    "Fawkes", "Fenrir", "Frodo", "Galadriel", "Gandalf", "Ghidorah",
    "Griffin", "Gryffin", "Havoc", "Hermione", "Hydra", "Icarus",
    "Jareth", "Kaida", "Khaleesi", "Kraken", "Legolas", "Leviathan",
    "Loki", "Lumina", "Lyra", "Magnus", "Merlin", "Midna", "Morgoth",
    "Mystic", "Nagini", "Navi", "Nebula", "Nereus", "Nyx", "Oberon",
    "Onyxia", "Orion", "Osiris", "Pegasus", "Persephone", "Phoenix",
    "Puck", "Quetzal", "Raiden", "Riven", "Rowena", "Rune", "Saphira",
    "Sauron", "Selene", "Shadowfax", "Smaug", "Starlight", "Stormborn",
    "Sylvanas", "Tiamat", "Titania", "Triton", "Tyrael", "Umbriel",
    "Valerion", "Valkyrie", "Vesper", "Vex", "Wisp", "Xanathar",
    "Xyris", "Ysera", "Zelda", "Zephyr", "Zephyra", "Alaric", "Auriel",
    "Balthazar", "Calypso", "Circe", "Drakon", "Elara", "Fable",
    "Glimmer", "Helios", "Isolde", "Jinn", "Kirin", "Lorien"
  ],
  unique: [
    "Aelious", "Bodhi", "Caelum", "Dune", "Elowen", "Fjord", "Gatsby",
    "Havana", "Indigo", "Juniper", "Kairos", "Lazuli", "Marvel", "Nixie",
    "Oasis", "Poet", "Quasar", "Rhapsody", "Solstice", "Theory",
    "Umber", "Vale", "Whimsy", "Xen", "Yonder", "Zephyrine", "Amaranth",
    "Bexley", "Calix", "Darwin", "Echoes", "Fable", "Galaxy", "Harbor",
    "Iluka", "Jinx", "Kestrel", "Lotus", "Mosaic", "Nebulae", "Oriole",
    "Padme", "Quest", "Reverie", "Senna", "Tundra", "Ukiyo", "Vega",
    "Wilder", "Xylo", "Yuki", "Zenith", "Akira", "Brizo", "Cypress",
    "Delta", "Elysium", "Flair", "Glimmer", "Halcyon", "Iniko", "Juno",
    "Kismet", "Lyric", "Meridian", "Noble", "Onyx", "Peregrine", "Quill",
    "Riven", "Sable", "Trove", "Umi", "Valkyrie", "Waverly", "Xanthe",
    "Yara", "Zinnia", "Arrow", "Bronte", "Cove", "Drift", "Emrys",
    "Frost", "Grove", "Haven", "Irie", "Journey", "Karma", "Lark",
    "Meadow", "North", "Ode", "Prairie", "Quart", "Rune", "Sage"
  ],
  cool: [
    "Ace", "Blade", "Cruz", "Dagger", "Enzo", "Fury", "Ghost", "Hawk",
    "Ice", "Jagger", "Knox", "Legend", "Maverick", "Nitro", "Onyx",
    "Phoenix", "Quake", "Rebel", "Shadow", "Thunder", "Urban", "Venom",
    "Wolf", "Xander", "Yoshi", "Zero", "Arrow", "Bolt", "Cruze", "Draco",
    "Edge", "Flame", "Gunner", "Havoc", "Iron", "Jett", "Krypto",
    "Lynx", "Matrix", "Neon", "Odin", "Pulse", "Quest", "Raptor",
    "Steel", "Titan", "Ultra", "Vortex", "Warp", "XL", "Yin", "Zen",
    "Alpha", "Blitz", "Crash", "Diesel", "Echo", "Flash", "Grit",
    "Hades", "Inferno", "Jinx", "Kilo", "Laser", "Mace", "Nova",
    "Ozone", "Prism", "Quartz", "Riot", "Sonic", "Tank", "Unity",
    "Vice", "Whip", "X-Ray", "Yield", "Zoom", "Atlas", "Brute", "Clutch",
    "Dash", "Eon", "Fang", "Gauge", "Hex", "Impulse", "Jolt", "Knife",
    "Lucid", "Mech", "Nuke", "Optix", "Pixel", "Quad", "Rocket"
  ],
  baby: [
    "Tiny", "Peanut", "Button", "Pip", "Bean", "Midge", "Boo", "Dot",
    "Mini", "Pebble", "Sprout", "Teeny", "Bitty", "Cub", "Bambino",
    "Junior", "Little One", "Pup", "Kit", "Wee", "Fawn", "Hatchling",
    "Smalls", "Nano", "Atom", "Mite", "Babe", "Baby", "Doll", "Elf",
    "Fledgling", "Gosling", "Half-Pint", "Itsy", "Jellybean", "Kid",
    "Lamb", "Micro", "Niblet", "Pee-wee", "Quark", "Runt", "Shorty",
    "Tadpole", "Uno", "Wisp", "X-Small", "Yolk", "Zig", "Bambi",
    "Chip", "Ducky", "Elfin", "Filly", "Gnome", "Hopper", "Inch",
    "Joey", "Kiddo", "Lil Bit", "Mouse", "Nugget", "Oopsy", "Piglet",
    "Quarter", "Roo", "Squirt", "Thumbelina", "Wren", "Babycakes",
    "Cherub", "Darling", "Ewok", "Fairy", "Guppy", "Hummingbird",
    "Imp", "Jackpot", "Keiki", "Lullaby", "Munchkin", "Newt", "Olive",
    "Petite", "Quail", "Rascal", "Sweetie", "Titch", "Velvet", "Wobble",
    "Yum Yum", "Zuzu", "Binkie", "Cozy", "Doodle", "Fuzz", "Giggle"
  ],
};

const faqTemplates = (name, icon) => [
  {
    q: `What are the most popular ${name} names?`,
    a: `Popular ${name} names include classic choices widely loved by pet owners and enthusiasts. For male ${name}s ${icon}, names like Max, Charlie, and Buddy are timeless favorites. For female ${name}s ${icon}, Bella, Luna, and Daisy tend to top the charts. Browse our full collection above to find even more options tailored to your preferences.`,
  },
  {
    q: `How do I choose the best name for my ${name}?`,
    a: `Choosing the perfect name for your ${name} ${icon} depends on their personality, appearance, and your personal taste! Observe your ${name}'s unique behaviors — are they playful or calm? Bold or shy? Pick a name that feels right when you say it aloud. Short, 1-2 syllable names often work best as they are easier for animals to recognize and respond to.`,
  },
  {
    q: `Can I use human names for my ${name}?`,
    a: `Absolutely! Human names are very popular for ${name}s ${icon}. Names like Oliver, Sophie, Jack, or Emma work wonderfully and add a personal, meaningful touch. Many pet owners prefer human names because they create a stronger emotional connection and feel more like a family member than just a pet.`,
  },
  {
    q: `What are some unique ${name} names?`,
    a: `For unique ${name} names ${icon}, consider fantasy-inspired options, names from foreign languages, or creative invented combinations. Our Fantasy Names and Unique Names categories feature one-of-a-kind options drawn from mythology, literature, and pure imagination. You can also draw inspiration from your favorite books, movies, or video games!`,
  },
  {
    q: `Should my ${name}'s name be easy to pronounce?`,
    a: `Yes! Choose a name that is easy for you and your family to say consistently ${icon}. Avoid names that sound too similar to common commands (like "Kit" for "Sit"). A clear, distinct name helps your ${name} recognize when you are calling them and strengthens training effectiveness.`,
  },
];

function pickRandom(arr, count) {
  const shuffled = [...arr].sort(() => Math.random() - 0.5);
  return shuffled.slice(0, count);
}

// ── Animal definitions (238 animals) ────────────────────────────────
const animals = [
  { slug: "dog", name: "Dog", icon: "🐕", description: "Dogs are loyal companions full of personality. Find the perfect name for your canine friend!" },
  { slug: "cat", name: "Cat", icon: "🐱", description: "Cats are mysterious and elegant creatures. Discover a name that matches their unique charm." },
  { slug: "fox", name: "Fox", icon: "🦊", description: "Foxes are clever and agile. Pick a name as cunning and swift as your foxy friend." },
  { slug: "bear", name: "Bear", icon: "🐻", description: "Bears are powerful and majestic. Choose a strong name for this mighty animal." },
  { slug: "rabbit", name: "Rabbit", icon: "🐰", description: "Rabbits are gentle and playful. Find a sweet name for your bunny companion." },
  { slug: "hamster", name: "Hamster", icon: "🐹", description: "Hamsters are tiny bundles of energy. Pick an adorable name for your little friend." },
  { slug: "guinea-pig", name: "Guinea Pig", icon: "🐹", description: "Guinea pigs are social and vocal. Find a charming name for your squeaky pal." },
  { slug: "horse", name: "Horse", icon: "🐴", description: "Horses are noble and powerful. Choose a majestic name for your equine friend." },
  { slug: "parrot", name: "Parrot", icon: "🦜", description: "Parrots are colorful and chatty. Find a vibrant name for your feathered companion." },
  { slug: "turtle", name: "Turtle", icon: "🐢", description: "Turtles are wise and patient. Pick a timeless name for your shelled friend." },
  { slug: "fish", name: "Fish", icon: "🐠", description: "Fish bring aquatic beauty to any space. Discover a flowing name for your swimming friend." },
  { slug: "snake", name: "Snake", icon: "🐍", description: "Snakes are mysterious and graceful. Choose a sleek name for your serpentine companion." },
  { slug: "lizard", name: "Lizard", icon: "🦎", description: "Lizards are fascinating and adaptable. Find a cool name for your scaly friend." },
  { slug: "frog", name: "Frog", icon: "🐸", description: "Frogs are cheerful and jumpy. Pick a fun name for your amphibious buddy." },
  { slug: "hedgehog", name: "Hedgehog", icon: "🦔", description: "Hedgehogs are prickly but sweet. Find a cute name for your spiky friend." },
  { slug: "ferret", name: "Ferret", icon: "🦡", description: "Ferrets are curious and playful. Choose a mischievous name for your furry pal." },
  { slug: "chinchilla", name: "Chinchilla", icon: "🐿️", description: "Chinchillas are soft and adorable. Pick a fluffy name for your cuddly friend." },
  { slug: "mouse", name: "Mouse", icon: "🐭", description: "Mice are tiny and clever. Find a sweet name for your miniature companion." },
  { slug: "rat", name: "Rat", icon: "🐀", description: "Rats are intelligent and affectionate. Choose a smart name for your rodent buddy." },
  { slug: "bird", name: "Bird", icon: "🐦", description: "Birds bring song and color to life. Find a melodic name for your feathered friend." },
  { slug: "duck", name: "Duck", icon: "🦆", description: "Ducks are charming and quacky. Pick a delightful name for your waterfowl friend." },
  { slug: "goose", name: "Goose", icon: "🦆", description: "Geese are loyal and protective. Choose a bold name for your honking companion." },
  { slug: "chicken", name: "Chicken", icon: "🐔", description: "Chickens are funny and productive. Find a clucky name for your feathered friend." },
  { slug: "pig", name: "Pig", icon: "🐷", description: "Pigs are smart and charming. Pick a delightful name for your porcine pal." },
  { slug: "cow", name: "Cow", icon: "🐮", description: "Cows are gentle giants. Find a warm name for your bovine companion." },
  { slug: "sheep", name: "Sheep", icon: "🐑", description: "Sheep are gentle and fluffy. Choose a soft name for your woolly friend." },
  { slug: "goat", name: "Goat", icon: "🐐", description: "Goats are playful and curious. Pick a spirited name for your caprine pal." },
  { slug: "alpaca", name: "Alpaca", icon: "🦙", description: "Alpacas are gentle and fluffy. Find a soft name for your camelid companion." },
  { slug: "llama", name: "Llama", icon: "🦙", description: "Llamas are proud and sassy. Choose a regal name for your woolly friend." },
  { slug: "donkey", name: "Donkey", icon: "🫏", description: "Donkeys are stubborn but lovable. Pick a hearty name for your long-eared pal." },
  { slug: "elephant", name: "Elephant", icon: "🐘", description: "Elephants are wise and majestic. Find a grand name for this gentle giant." },
  { slug: "lion", name: "Lion", icon: "🦁", description: "Lions are the kings of the jungle. Choose a royal name for this magnificent beast." },
  { slug: "tiger", name: "Tiger", icon: "🐯", description: "Tigers are powerful and striped. Pick a fierce name for this striped predator." },
  { slug: "leopard", name: "Leopard", icon: "🐆", description: "Leopards are sleek and spotted. Find an elegant name for this spotted hunter." },
  { slug: "cheetah", name: "Cheetah", icon: "🐆", description: "Cheetahs are the fastest land animals. Choose a swift name for this speedy cat." },
  { slug: "wolf", name: "Wolf", icon: "🐺", description: "Wolves are loyal pack animals. Pick a powerful name for this wild canine." },
  { slug: "coyote", name: "Coyote", icon: "🐺", description: "Coyotes are clever survivors. Find a cunning name for this adaptable hunter." },
  { slug: "hyena", name: "Hyena", icon: "🦡", description: "Hyenas are social and vocal. Choose a unique name for this misunderstood animal." },
  { slug: "panda", name: "Panda", icon: "🐼", description: "Pandas are adorable bamboo lovers. Pick a cuddly name for this black-and-white bear." },
  { slug: "koala", name: "Koala", icon: "🐨", description: "Koalas are sleepy eucalyptus eaters. Find a relaxed name for this marsupial friend." },
  { slug: "kangaroo", name: "Kangaroo", icon: "🦘", description: "Kangaroos are bouncy and strong. Choose a hoppy name for this Australian icon." },
  { slug: "raccoon", name: "Raccoon", icon: "🦝", description: "Raccoons are clever bandits. Pick a sneaky name for this masked mischief-maker." },
  { slug: "squirrel", name: "Squirrel", icon: "🐿️", description: "Squirrels are energetic nut hoarders. Find a perky name for this bushy-tailed friend." },
  { slug: "chipmunk", name: "Chipmunk", icon: "🐿️", description: "Chipmunks are tiny and cheeky. Choose a peppy name for this striped cutie." },
  { slug: "otter", name: "Otter", icon: "🦦", description: "Otters are playful swimmers. Pick a joyful name for this aquatic acrobat." },
  { slug: "beaver", name: "Beaver", icon: "🦫", description: "Beavers are hard-working builders. Find a sturdy name for this diligent rodent." },
  { slug: "skunk", name: "Skunk", icon: "🦨", description: "Skunks are distinctive and bold. Choose a standout name for this striped stinker." },
  { slug: "deer", name: "Deer", icon: "🦌", description: "Deer are graceful and gentle. Pick an elegant name for this woodland beauty." },
  { slug: "moose", name: "Moose", icon: "🫎", description: "Moose are massive and majestic. Find a grand name for this northern giant." },
  { slug: "reindeer", name: "Reindeer", icon: "🦌", description: "Reindeer are hardy Arctic travelers. Choose a magical name for this holiday icon." },
  { slug: "giraffe", name: "Giraffe", icon: "🦒", description: "Giraffes are towering and graceful. Pick a lofty name for this long-necked beauty." },
  { slug: "zebra", name: "Zebra", icon: "🦓", description: "Zebras are striped and spirited. Find a bold name for this black-and-white equine." },
  { slug: "hippopotamus", name: "Hippopotamus", icon: "🦛", description: "Hippos are powerful river dwellers. Choose a mighty name for this massive mammal." },
  { slug: "rhinoceros", name: "Rhinoceros", icon: "🦏", description: "Rhinos are armored titans. Pick a strong name for this horned heavyweight." },
  { slug: "gorilla", name: "Gorilla", icon: "🦍", description: "Gorillas are gentle but powerful. Find a noble name for this great ape." },
  { slug: "monkey", name: "Monkey", icon: "🐒", description: "Monkeys are playful and smart. Choose a fun name for this primate pal." },
  { slug: "chimpanzee", name: "Chimpanzee", icon: "🐒", description: "Chimpanzees are our closest relatives. Pick a clever name for this intelligent ape." },
  { slug: "orangutan", name: "Orangutan", icon: "🦧", description: "Orangutans are gentle forest dwellers. Find a wise name for this red ape." },
  { slug: "lemur", name: "Lemur", icon: "🐒", description: "Lemurs are quirky primates. Choose a unique name for this ring-tailed friend." },
  { slug: "dolphin", name: "Dolphin", icon: "🐬", description: "Dolphins are intelligent and playful. Pick a joyful name for this ocean acrobat." },
  { slug: "whale", name: "Whale", icon: "🐋", description: "Whales are magnificent ocean giants. Find a majestic name for this deep-sea wonder." },
  { slug: "shark", name: "Shark", icon: "🦈", description: "Sharks are powerful ocean predators. Choose a fierce name for this aquatic hunter." },
  { slug: "octopus", name: "Octopus", icon: "🐙", description: "Octopuses are clever and adaptable. Pick a smart name for this eight-armed genius." },
  { slug: "jellyfish", name: "Jellyfish", icon: "🪼", description: "Jellyfish are ethereal drifters. Find a dreamy name for this translucent beauty." },
  { slug: "seahorse", name: "Seahorse", icon: "🐴", description: "Seahorses are delicate and unique. Choose a whimsical name for this tiny marvel." },
  { slug: "starfish", name: "Starfish", icon: "🌟", description: "Starfish are colorful ocean dwellers. Pick a bright name for this five-armed friend." },
  { slug: "crab", name: "Crab", icon: "🦀", description: "Crabs are sideways scuttlers. Find a pinchy name for this crustacean companion." },
  { slug: "lobster", name: "Lobster", icon: "🦞", description: "Lobsters are clawed bottom-dwellers. Choose a grand name for this seafood star." },
  { slug: "penguin", name: "Penguin", icon: "🐧", description: "Penguins are tuxedoed charmers. Pick a dapper name for this flightless friend." },
  { slug: "seal", name: "Seal", icon: "🦭", description: "Seals are playful ocean pups. Find a sleek name for this aquatic mammal." },
  { slug: "walrus", name: "Walrus", icon: "🦭", description: "Walruses are tusked Arctic giants. Choose a mighty name for this whiskered wonder." },
  { slug: "polar-bear", name: "Polar Bear", icon: "🐻‍❄️", description: "Polar bears are Arctic royalty. Pick a cool name for this snow-white predator." },
  { slug: "eagle", name: "Eagle", icon: "🦅", description: "Eagles are majestic sky hunters. Find a soaring name for this noble raptor." },
  { slug: "hawk", name: "Hawk", icon: "🦅", description: "Hawks are keen-eyed hunters. Choose a sharp name for this skilled predator." },
  { slug: "owl", name: "Owl", icon: "🦉", description: "Owls are wise night hunters. Pick a thoughtful name for this silent flyer." },
  { slug: "falcon", name: "Falcon", icon: "🦅", description: "Falcons are the fastest birds. Find a swift name for this diving speedster." },
  { slug: "raven", name: "Raven", icon: "🐦‍⬛", description: "Ravens are intelligent and mysterious. Choose a dark name for this clever corvid." },
  { slug: "crow", name: "Crow", icon: "🐦‍⬛", description: "Crows are smart and resourceful. Pick a bright name for this black-feathered brain." },
  { slug: "peacock", name: "Peacock", icon: "🦚", description: "Peacocks are stunning show-offs. Find a proud name for this colorful beauty." },
  { slug: "swan", name: "Swan", icon: "🦢", description: "Swans are elegant water birds. Pick a graceful name for this pristine beauty." },
  { slug: "butterfly", name: "Butterfly", icon: "🦋", description: "Butterflies are delicate pollinators. Find a light name for this winged wonder." },
  { slug: "bee", name: "Bee", icon: "🐝", description: "Bees are busy pollinators. Choose a buzzy name for this hardworking insect." },
  { slug: "ladybug", name: "Ladybug", icon: "🐞", description: "Ladybugs are lucky garden friends. Pick a sweet name for this spotted beetle." },
  { slug: "ant", name: "Ant", icon: "🐜", description: "Ants are tiny but mighty workers. Find a strong name for this miniature marvel." },
  { slug: "spider", name: "Spider", icon: "🕷️", description: "Spiders are skilled web artists. Choose a crafty name for this eight-legged friend." },
  { slug: "scorpion", name: "Scorpion", icon: "🦂", description: "Scorpions are armored stingers. Pick a fiery name for this desert dweller." },
  { slug: "dragon", name: "Dragon", icon: "🐉", description: "Dragons are legendary fire-breathers. Find an epic name for this mythical beast." },
  { slug: "unicorn", name: "Unicorn", icon: "🦄", description: "Unicorns are magical horned horses. Choose a sparkly name for this mythical beauty." },
  { slug: "phoenix", name: "Phoenix", icon: "🐦‍🔥", description: "Phoenixes are immortal fire birds. Pick a blazing name for this legendary creature." },
  { slug: "griffin", name: "Griffin", icon: "🦅", description: "Griffins are majestic lion-eagle hybrids. Find a royal name for this mythical guardian." },
  { slug: "pegasus", name: "Pegasus", icon: "🐴", description: "Pegasus is a winged horse of legend. Choose an airy name for this flying steed." },
  { slug: "mermaid", name: "Mermaid", icon: "🧜‍♀️", description: "Mermaids are enchanting sea beings. Pick a magical name for this aquatic beauty." },
  { slug: "werewolf", name: "Werewolf", icon: "🐺", description: "Werewolves are shapeshifting moon creatures. Find a howling name for this lunar beast." },
  { slug: "bat", name: "Bat", icon: "🦇", description: "Bats are night-flying mammals. Pick a shadowy name for this echolocating friend." },
  { slug: "camel", name: "Camel", icon: "🐪", description: "Camels are desert ships. Find a hardy name for this humped traveler." },
  { slug: "gazelle", name: "Gazelle", icon: "🦌", description: "Gazelles are swift and graceful. Pick a fleet name for this elegant runner." },
  { slug: "anteater", name: "Anteater", icon: "🐜", description: "Anteaters are long-nosed insect lovers. Find a unique name for this specialized hunter." },
  { slug: "sloth", name: "Sloth", icon: "🦥", description: "Sloths are slow-moving tree dwellers. Choose a laid-back name for this relaxed friend." },
  { slug: "armadillo", name: "Armadillo", icon: "🦔", description: "Armadillos are armored diggers. Pick a tough name for this plated creature." },
  { slug: "porcupine", name: "Porcupine", icon: "🦔", description: "Porcupines are quilled defenders. Find a prickly name for this spiky rodent." },
  { slug: "meerkat", name: "Meerkat", icon: "🦡", description: "Meerkats are vigilant desert dwellers. Choose an alert name for this standing sentinel." },
  { slug: "wombat", name: "Wombat", icon: "🦡", description: "Wombats are burrowing marsupials. Pick a sturdy name for this cube-pooping friend." },
  { slug: "platypus", name: "Platypus", icon: "🦆", description: "Platypuses are bizarre egg-laying mammals. Find a quirky name for this unique creature." },
  { slug: "tasmanian-devil", name: "Tasmanian Devil", icon: "🦡", description: "Tasmanian devils are fierce little marsupials. Choose a spirited name for this whirlwind friend." },
  { slug: "dingo", name: "Dingo", icon: "🐕", description: "Dingoes are wild Australian dogs. Pick a rugged name for this outback hunter." },
  { slug: "jackal", name: "Jackal", icon: "🐺", description: "Jackals are cunning scavengers. Find a sly name for this desert opportunist." },
  { slug: "fennec-fox", name: "Fennec Fox", icon: "🦊", description: "Fennec foxes are tiny desert foxes with huge ears. Choose an adorable name for this big-eared cutie." },
  { slug: "arctic-fox", name: "Arctic Fox", icon: "🦊", description: "Arctic foxes are snow-white survivors. Pick a frosty name for this northern beauty." },
  { slug: "red-panda", name: "Red Panda", icon: "🐼", description: "Red pandas are adorable bamboo eaters. Find a cute name for this tree-dwelling charmer." },
  { slug: "snow-leopard", name: "Snow Leopard", icon: "🐆", description: "Snow leopards are ghostly mountain cats. Choose an elusive name for this high-altitude hunter." },
  { slug: "jaguar", name: "Jaguar", icon: "🐆", description: "Jaguars are powerful jungle cats. Pick a fierce name for this spotted predator." },
  { slug: "puma", name: "Puma", icon: "🐆", description: "Pumas are silent mountain lions. Find a stealthy name for this solitary cat." },
  { slug: "lynx", name: "Lynx", icon: "🐱", description: "Lynxes are tufted-eared hunters. Choose a sharp name for this northern feline." },
  { slug: "bobcat", name: "Bobcat", icon: "🐱", description: "Bobcats are stubby-tailed wildcats. Pick a feisty name for this fierce little hunter." },
  { slug: "ocelot", name: "Ocelot", icon: "🐆", description: "Ocelots are beautifully spotted small cats. Find a sleek name for this jungle beauty." },
  { slug: "caracal", name: "Caracal", icon: "🐱", description: "Caracals are tufted-ear desert cats. Choose an exotic name for this athletic hunter." },
  { slug: "serval", name: "Serval", icon: "🐱", description: "Servals are long-legged African cats. Pick a leggy name for this tall-eared beauty." },
  { slug: "manatee", name: "Manatee", icon: "🦭", description: "Manatees are gentle sea cows. Find a peaceful name for this slow-moving marine mammal." },
  { slug: "dugong", name: "Dugong", icon: "🦭", description: "Dugongs are peaceful sea grazers. Choose a serene name for this marine herbivore." },
  { slug: "narwhal", name: "Narwhal", icon: "🐋", description: "Narwhals are Arctic unicorns of the sea. Pick a mystical name for this tusked whale." },
  { slug: "beluga", name: "Beluga", icon: "🐋", description: "Belugas are white Arctic whales. Find a bright name for this smiling sea creature." },
  { slug: "orca", name: "Orca", icon: "🐋", description: "Orcas are intelligent ocean hunters. Choose a powerful name for this apex predator." },
  { slug: "sperm-whale", name: "Sperm Whale", icon: "🐋", description: "Sperm whales are deep-diving giants. Pick a profound name for this mighty cetacean." },
  { slug: "humpback-whale", name: "Humpback Whale", icon: "🐋", description: "Humpback whales are singing ocean travelers. Find a melodic name for this majestic singer." },
  { slug: "manta-ray", name: "Manta Ray", icon: "🦈", description: "Manta rays are graceful ocean flyers. Choose an elegant name for this winged swimmer." },
  { slug: "stingray", name: "Stingray", icon: "🦈", description: "Stingrays are flat ocean gliders. Pick a smooth name for this bottom-dwelling beauty." },
  { slug: "swordfish", name: "Swordfish", icon: "🐟", description: "Swordfish are fast ocean gladiators. Find a sharp name for this bill-nosed fighter." },
  { slug: "marlin", name: "Marlin", icon: "🐟", description: "Marlins are sleek speed demons. Choose a speedy name for this ocean racer." },
  { slug: "tuna", name: "Tuna", icon: "🐟", description: "Tuna are powerful open-ocean swimmers. Pick a strong name for this streamlined fish." },
  { slug: "salmon", name: "Salmon", icon: "🐟", description: "Salmon are determined upstream swimmers. Find a resilient name for this journeying fish." },
  { slug: "clownfish", name: "Clownfish", icon: "🐠", description: "Clownfish are colorful reef dwellers. Choose a bright name for this anemone friend." },
  { slug: "pufferfish", name: "Pufferfish", icon: "🐡", description: "Pufferfish are spiky inflators. Pick a round name for this defensive cutie." },
  { slug: "anglerfish", name: "Anglerfish", icon: "🐟", description: "Anglerfish are deep-sea light-bearers. Find a glowing name for this bioluminescent hunter." },
  { slug: "axolotl", name: "Axolotl", icon: "🦎", description: "Axolotls are smiling salamanders. Choose an adorable name for this regenerating wonder." },
  { slug: "iguana", name: "Iguana", icon: "🦎", description: "Iguanas are sun-loving lizards. Pick a tropical name for this green tree-dweller." },
  { slug: "chameleon", name: "Chameleon", icon: "🦎", description: "Chameleons are color-changing masters. Find a versatile name for this camouflaging friend." },
  { slug: "gecko", name: "Gecko", icon: "🦎", description: "Geckos are sticky-footed climbers. Choose a clingy name for this wall-walking buddy." },
  { slug: "komodo-dragon", name: "Komodo Dragon", icon: "🦎", description: "Komodo dragons are giant monitor lizards. Pick a fearsome name for this apex reptile." },
  { slug: "crocodile", name: "Crocodile", icon: "🐊", description: "Crocodiles are ancient predators. Find a powerful name for this armored reptile." },
  { slug: "alligator", name: "Alligator", icon: "🐊", description: "Alligators are swamp-dwelling reptiles. Choose a snappy name for this broad-snouted hunter." },
  { slug: "cobra", name: "Cobra", icon: "🐍", description: "Cobras are hooded venomous snakes. Pick a hypnotic name for this iconic serpent." },
  { slug: "python", name: "Python", icon: "🐍", description: "Pythons are massive constrictors. Find a squeezing name for this powerful snake." },
  { slug: "rattlesnake", name: "Rattlesnake", icon: "🐍", description: "Rattlesnakes are warning-tail vipers. Choose a buzzy name for this desert rattler." },
  { slug: "anaconda", name: "Anaconda", icon: "🐍", description: "Anacondas are giant water snakes. Pick a massive name for this Amazonian heavyweight." },
  { slug: "tarantula", name: "Tarantula", icon: "🕷️", description: "Tarantulas are fuzzy eight-legged friends. Find a hairy name for this gentle giant spider." },
  { slug: "praying-mantis", name: "Praying Mantis", icon: "🦗", description: "Praying mantises are patient hunters. Choose a zen name for this folded-arm predator." },
  { slug: "stick-insect", name: "Stick Insect", icon: "🦗", description: "Stick insects are master camouflagers. Pick a twiggy name for this hiding expert." },
  { slug: "caterpillar", name: "Caterpillar", icon: "🐛", description: "Caterpillars are hungry future butterflies. Find a wiggly name for this munching friend." },
  { slug: "snail", name: "Snail", icon: "🐌", description: "Snails are slow but steady travelers. Choose a patient name for this shelled crawler." },
  { slug: "earthworm", name: "Earthworm", icon: "🪱", description: "Earthworms are underground soil heroes. Pick a earthy name for this wiggly gardener." },
  { slug: "cockroach", name: "Cockroach", icon: "🪳", description: "Cockroaches are ultimate survivors. Find a resilient name for this indestructible insect." },
  { slug: "firefly", name: "Firefly", icon: "🪲", description: "Fireflies are magical glowing beetles. Choose a luminous name for this nighttime sparkler." },
  { slug: "beetle", name: "Beetle", icon: "🪲", description: "Beetles are armored insects. Pick a sturdy name for this hard-shelled explorer." },
  { slug: "dragonfly", name: "Dragonfly", icon: "🪰", description: "Dragonflies are agile aerial hunters. Find a swift name for this iridescent flyer." },
  { slug: "grasshopper", name: "Grasshopper", icon: "🦗", description: "Grasshoppers are leaping musicians. Choose a jumpy name for this chirping friend." },
  { slug: "cricket", name: "Cricket", icon: "🦗", description: "Crickets are nighttime singers. Pick a musical name for this chirpy companion." },
  { slug: "termite", name: "Termite", icon: "🐜", description: "Termites are colony-building architects. Find a structural name for this wood-eating engineer." },
  { slug: "wasp", name: "Wasp", icon: "🐝", description: "Wasps are buzzing predators. Choose a stinging name for this yellow-and-black defender." },
  { slug: "mosquito", name: "Mosquito", icon: "🦟", description: "Mosquitoes are tiny buzzing pests. Pick a whiny name for this blood-sipping flyer." },
  { slug: "centipede", name: "Centipede", icon: "🦂", description: "Centipedes are many-legged hunters. Find a leggy name for this speedy arthropod." },
  { slug: "millipede", name: "Millipede", icon: "🪱", description: "Millipedes are countless-legged crawlers. Choose a curly name for this segmented friend." },
  { slug: "hermit-crab", name: "Hermit Crab", icon: "🦀", description: "Hermit crabs are shell-swapping wanderers. Pick a homely name for this mobile troglodyte." },
  { slug: "pigeon", name: "Pigeon", icon: "🕊️", description: "Pigeons are city-dwelling birds. Choose an urban name for this cooing companion." },
  { slug: "sparrow", name: "Sparrow", icon: "🐦", description: "Sparrows are cheerful little birds. Pick a tiny name for this friendly flyer." },
  { slug: "blue-jay", name: "Blue Jay", icon: "🐦", description: "Blue jays are bold and blue. Find a vibrant name for this colorful corvid." },
  { slug: "cardinal", name: "Cardinal", icon: "🐦", description: "Cardinals are brilliant red songbirds. Choose a crimson name for this backyard beauty." },
  { slug: "robin", name: "Robin", icon: "🐦", description: "Robins are springtime heralds. Pick a cheerful name for this red-breasted friend." },
  { slug: "hummingbird", name: "Hummingbird", icon: "🐦", description: "Hummingbirds are tiny aerial jewels. Find a rapid name for this hovering wonder." },
  { slug: "woodpecker", name: "Woodpecker", icon: "🐦", description: "Woodpeckers are tree-drumming carpenters. Choose a rhythmic name for this pecking pro." },
  { slug: "pelican", name: "Pelican", icon: "🦤", description: "Pelicans are big-beaked fish catchers. Pick a pouchy name for this seabird friend." },
  { slug: "seagull", name: "Seagull", icon: "🕊️", description: "Seagulls are coastal opportunists. Find a screechy name for this beach bird." },
  { slug: "albatross", name: "Albatross", icon: "🕊️", description: "Albatrosses are ocean-wandering giants. Choose a far-flying name for this long-winged traveler." },
  { slug: "kiwi", name: "Kiwi", icon: "🥝", description: "Kiwis are flightless New Zealand birds. Pick a unique name for this nocturnal forager." },
  { slug: "ostrich", name: "Ostrich", icon: "🦤", description: "Ostriches are the biggest birds on Earth. Find a towering name for this speedy runner." },
  { slug: "emu", name: "Emu", icon: "🦤", description: "Emus are tall Australian runners. Choose a leggy name for this flightless wonder." },
  { slug: "toucan", name: "Toucan", icon: "🦜", description: "Toucans are big-billed tropical birds. Pick a fruity name for this colorful flyer." },
  { slug: "macaw", name: "Macaw", icon: "🦜", description: "Macaws are brilliantly colored parrots. Find a vibrant name for this tropical beauty." },
  { slug: "cockatoo", name: "Cockatoo", icon: "🦜", description: "Cockatoos are crested and charismatic. Choose a showy name for this head-turning parrot." },
  { slug: "lovebird", name: "Lovebird", icon: "🦜", description: "Lovebirds are affectionate small parrots. Pick a sweet name for this cuddly pair." },
  { slug: "budgie", name: "Budgie", icon: "🦜", description: "Budgies are cheerful little parakeets. Find a chirpy name for this tiny talker." },
  { slug: "canary", name: "Canary", icon: "🐦", description: "Canaries are sweet-singing birds. Choose a melodic name for this yellow songster." },
  { slug: "finch", name: "Finch", icon: "🐦", description: "Finches are colorful seed-eaters. Pick a bright name for this tiny beaked friend." },
  { slug: "goldfish", name: "Goldfish", icon: "🐠", description: "Goldfish are classic aquarium pets. Find a shimmery name for this orange swimmer." },
  { slug: "betta-fish", name: "Betta Fish", icon: "🐠", description: "Betta fish are flowing-finned beauties. Choose an elegant name for this fighting fish." },
  { slug: "koi", name: "Koi", icon: "🐟", description: "Koi are ornamental pond fish. Pick a lucky name for this colorful swimmer." },
  { slug: "angelfish", name: "Angelfish", icon: "🐠", description: "Angelfish are tall, graceful swimmers. Find a heavenly name for this aqua beauty." },
  { slug: "guppy", name: "Guppy", icon: "🐟", description: "Guppies are tiny colorful fish. Choose a small name for this prolific breeder." },
  { slug: "tetra", name: "Tetra", icon: "🐟", description: "Tetras are small schooling fish. Pick a group name for this community swimmer." },
  { slug: "discus", name: "Discus", icon: "🐠", description: "Discus fish are regal aquarium royalty. Find a noble name for this disc-shaped beauty." },
  { slug: "cichlid", name: "Cichlid", icon: "🐟", description: "Cichlids are diverse intelligent fish. Choose a smart name for this territorial swimmer." },
  { slug: "sea-turtle", name: "Sea Turtle", icon: "🐢", description: "Sea turtles are ancient ocean voyagers. Pick a timeless name for this shelled swimmer." },
  { slug: "tortoise", name: "Tortoise", icon: "🐢", description: "Tortoises are long-lived land turtles. Find an enduring name for this slow-paced elder." },
  { slug: "tree-frog", name: "Tree Frog", icon: "🐸", description: "Tree frogs are colorful climbers. Choose a sticky name for this arboreal amphibian." },
  { slug: "toad", name: "Toad", icon: "🐸", description: "Toads are bumpy garden friends. Pick a warty name for this insect-eating buddy." },
  { slug: "salamander", name: "Salamander", icon: "🦎", description: "Salamanders are moist-skinned amphibians. Find a slick name for this forest dweller." },
  { slug: "newt", name: "Newt", icon: "🦎", description: "Newts are small aquatic salamanders. Choose a water-loving name for this regenerating friend." },
  { slug: "barn-owl", name: "Barn Owl", icon: "🦉", description: "Barn owls are heart-faced night hunters. Pick a ghostly name for this silent predator." },
  { slug: "great-horned-owl", name: "Great Horned Owl", icon: "🦉", description: "Great horned owls are powerful night predators. Find a fierce name for this tufted hunter." },
  { slug: "kookaburra", name: "Kookaburra", icon: "🐦", description: "Kookaburras are laughing Australian birds. Choose a jolly name for this giggling friend." },
  { slug: "puffin", name: "Puffin", icon: "🐧", description: "Puffins are clownish sea birds. Pick a colorful name for this beaked beauty." },
  { slug: "kingfisher", name: "Kingfisher", icon: "🐦", description: "Kingfishers are brilliant diving hunters. Find a regal name for this river-diving jewel." },
  { slug: "mockingbird", name: "Mockingbird", icon: "🐦", description: "Mockingbirds are master imitators. Choose a mimicking name for this versatile singer." },
  { slug: "nightingale", name: "Nightingale", icon: "🐦", description: "Nightingales are legendary night singers. Pick a melodious name for this musical bird." },
  { slug: "cuckoo", name: "Cuckoo", icon: "🐦", description: "Cuckoos are clock-calling birds. Find a timely name for this woodland caller." },
  { slug: "honey-badger", name: "Honey Badger", icon: "🦡", description: "Honey badgers are fearless fighters. Choose a tough name for this relentless warrior." },
  { slug: "wolverine", name: "Wolverine", icon: "🦡", description: "Wolverines are fierce northern predators. Pick a ferocious name for this snow fighter." },
  { slug: "badger", name: "Badger", icon: "🦡", description: "Badgers are stout diggers. Find a sturdy name for this underground sett dweller." },
  { slug: "weasel", name: "Weasel", icon: "🦡", description: "Weasels are tiny fierce hunters. Choose a sneaky name for this long-bodied predator." },
  { slug: "mink", name: "Mink", icon: "🦡", description: "Minks are sleek water-loving mustelids. Pick a glossy name for this furred swimmer." },
  { slug: "marten", name: "Marten", icon: "🦡", description: "Martens are agile tree climbers. Find a nimble name for this forest acrobat." },
  { slug: "mongoose", name: "Mongoose", icon: "🦡", description: "Mongooses are snake-fighting heroes. Choose a brave name for this cobra-tackling friend." },
  { slug: "yak", name: "Yak", icon: "🐃", description: "Yaks are shaggy highland cattle. Pick a lofty name for this Tibetan grazer." },
  { slug: "bison", name: "Bison", icon: "🦬", description: "Bison are massive prairie grazers. Find a powerful name for this American icon." },
  { slug: "buffalo", name: "Buffalo", icon: "🐃", description: "Buffaloes are sturdy water-loving bovines. Choose a strong name for this farm helper." },
  { slug: "ox", name: "Ox", icon: "🐂", description: "Oxen are powerful working cattle. Pick a sturdy name for this draft animal." },
  { slug: "musk-ox", name: "Musk Ox", icon: "🐃", description: "Musk oxen are shaggy Arctic survivors. Find a woolly name for this northern grazer." },
  { slug: "pronghorn", name: "Pronghorn", icon: "🦌", description: "Pronghorns are North America's fastest land animal. Choose a speedy name for this prairie runner." },
  { slug: "ibex", name: "Ibex", icon: "🐐", description: "Ibexes are cliff-climbing mountain goats. Pick a sure-footed name for this alpine acrobat." },
  { slug: "mountain-goat", name: "Mountain Goat", icon: "🐐", description: "Mountain goats are alpine climbers. Find a lofty name for this high-altitude dweller." },
  { slug: "bighorn-sheep", name: "Bighorn Sheep", icon: "🐑", description: "Bighorn sheep are head-butting mountain rams. Choose a tough name for this horned climber." },
  { slug: "wild-boar", name: "Wild Boar", icon: "🐗", description: "Wild boars are tusked forest foragers. Pick a rugged name for this bristled beast." },
  { slug: "warthog", name: "Warthog", icon: "🐗", description: "Warthogs are tusked African pigs. Find a comical name for this savanna grazer." },
  { slug: "tapir", name: "Tapir", icon: "🐖", description: "Tapirs are trunk-nosed forest dwellers. Choose a unique name for this prehistoric-looking friend." },
  { slug: "capybara", name: "Capybara", icon: "🦫", description: "Capybaras are chill giant rodents. Pick a relaxed name for this world's largest rodent." },
  { slug: "marmot", name: "Marmot", icon: "🐿️", description: "Marmots are chubby alpine rodents. Find a chunky name for this whistling mountain dweller." },
  { slug: "groundhog", name: "Groundhog", icon: "🐿️", description: "Groundhogs are weather-predicting diggers. Choose a shadowy name for this February celebrity." },
  { slug: "prairie-dog", name: "Prairie Dog", icon: "🐿️", description: "Prairie dogs are social burrowers. Pick a chatty name for this town-building rodent." },
  { slug: "jerboa", name: "Jerboa", icon: "🐭", description: "Jerboas are tiny hopping desert rodents. Find a jumpy name for this long-eared hopper." },
  { slug: "gerbil", name: "Gerbil", icon: "🐭", description: "Gerbils are active desert rodents. Choose a diggy name for this tunneling friend." },
  { slug: "vole", name: "Vole", icon: "🐭", description: "Voles are small meadow rodents. Pick a grassy name for this field-dwelling nibbler." },
  { slug: "lemming", name: "Lemming", icon: "🐭", description: "Lemmings are Arctic tundra rodents. Find a resilient name for this northern survivor." },
  { slug: "hyrax", name: "Hyrax", icon: "🐹", description: "Hyraxes are elephant relatives that look like rodents. Choose a surprising name for this rock dweller." },
  { slug: "pangolin", name: "Pangolin", icon: "🦔", description: "Pangolins are scaly anteaters. Pick a armored name for this threatened wonder." },
  { slug: "aardvark", name: "Aardvark", icon: "🐜", description: "Aardvarks are African termite eaters. Find an alphabetical name for this first-in-the-dictionary animal." },
];

if (!fs.existsSync(DATA_DIR)) {
  fs.mkdirSync(DATA_DIR, { recursive: true });
}

const allSlugs = [];
const animalsIndex = [];

animals.forEach((animal) => {
  const data = {
    slug: animal.slug,
    displayName: animal.name,
    icon: animal.icon,
    description: animal.description,
    metaDescription: `Discover the perfect name for your ${animal.name.toLowerCase()} ${animal.icon}! Browse 100 male, female, cute, funny, and fantasy names with our free animal name generator.`,
    maleNames: pickRandom(namePools.male, 20),
    femaleNames: pickRandom(namePools.female, 20),
    cuteNames: pickRandom(namePools.cute, 20),
    funnyNames: pickRandom(namePools.funny, 20),
    fantasyNames: pickRandom(namePools.fantasy, 20),
    uniqueNames: pickRandom(namePools.unique, 20),
    coolNames: pickRandom(namePools.cool, 20),
    babyNames: pickRandom(namePools.baby, 20),
    faq: faqTemplates(animal.name, animal.icon),
    seoTitle: `${animal.name} Name Generator - 100+ ${animal.name} Name Ideas ${animal.icon}`,
    seoDescription: `Find the perfect ${animal.name.toLowerCase()} name! Browse 100+ male, female, cute, funny, and fantasy ${animal.name.toLowerCase()} names ${animal.icon}. Free animal name generator with unique ideas.`,
    namingGuide: [
      `Consider your ${animal.name.toLowerCase()}'s personality — is it bold, shy, playful, or calm?`,
      `Look at physical traits like color, size, or unique markings.`,
      `Say the name out loud — does it sound natural and easy to call?`,
      `Avoid names that sound like common commands or other pets' names.`,
      `Try out a few names and see which one your ${animal.name.toLowerCase()} responds to best.`,
      `Short names (1-2 syllables) tend to be easiest for animals to learn and recognize.`,
    ],
  };

  const filePath = path.join(DATA_DIR, `${animal.slug}.json`);
  fs.writeFileSync(filePath, JSON.stringify(data, null, 2));
  allSlugs.push(animal.slug);
  animalsIndex.push({ slug: animal.slug, name: animal.name, icon: animal.icon });
});

fs.writeFileSync(
  path.join(DATA_DIR, "index.json"),
  JSON.stringify(animalsIndex, null, 2)
);

console.log(`✅ Generated ${animals.length} animal data files!`);
